spring.application.name=InfluenceX


# Local Database connection
#spring.datasource.url=jdbc:postgresql://localhost:5432/influencex
#spring.datasource.username=postgres
#spring.datasource.password=postgres

#Supabase Database connection
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000

server.port=${PORT:8080}

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB


# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.config.import=optional:classpath:.env.properties
google.client.id=${GOOGLE_CLIENT_ID}

razor.pay.test.key.id=${RAZOR_PAY_TEST_KEY_ID}
razor.pay.test.key.secret=${RAZOR_PAY_TEST_KEY_SECRET}


# ??? Email (Gmail SMTP) ???????????????????????????????????????????????????????
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

instagram.client-id=${META_APP_ID}
instagram.client-secret=${META_SECRET_KEY}
instagram.redirect-uri=http://localhost:8080/api/auth/oauth/instagram/callback



